# Generated by Django 4.2.7 on 2026-01-26 02:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.UUIDField(db_comment='외부 API용 고유 식별자', default=uuid.uuid4, editable=False, unique=True)),
                ('login_id', models.CharField(db_comment='사용자가 입력한 ID', max_length=20, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('nickname', models.CharField(max_length=20)),
                ('face_vector', models.JSONField(blank=True, db_comment='512차원 얼굴 벡터', null=True)),
                ('voice_vector', models.JSONField(blank=True, db_comment='256차원 음성 벡터', null=True)),
                ('is_verified', models.BooleanField(db_comment='생체 정보 등록 완료 여부', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='회원가입 일시')),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_comment='계정 활성화 상태', default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deletion_reason', models.CharField(blank=True, choices=[('INCONVENIENT', '사용이 불편함'), ('PRIVACY', '개인정보 유출 우려'), ('NOT_USED', '자주 사용하지 않음'), ('OTHER', '기타')], db_comment='탈퇴 사유', max_length=20, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.AutoField(db_comment='기기 고유 식별자', primary_key=True, serialize=False)),
                ('device_uuid', models.CharField(db_comment='기기 고유 UUID', max_length=100, unique=True)),
                ('device_name', models.CharField(blank=True, db_comment='기기 기본 이름', max_length=50, null=True)),
                ('device_type', models.CharField(blank=True, db_comment='디바이스 기종', max_length=50, null=True)),
                ('firmware_version', models.CharField(blank=True, db_comment='펌웨어 버전', max_length=20, null=True)),
                ('last_connected_at', models.DateTimeField(blank=True, db_comment='마지막 연결 시각', null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True, db_comment='기기 등록 일시')),
            ],
            options={
                'db_table': 'device',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('verification_id', models.AutoField(db_comment='이메일 인증 고유 식별자 (PK)', primary_key=True, serialize=False)),
                ('email', models.EmailField(db_comment='인증 대상 이메일 주소', max_length=100)),
                ('verification_code', models.CharField(db_comment='6자리 인증 코드', max_length=6)),
                ('is_verified', models.BooleanField(db_comment='인증 완료 여부 (True: 완료, False: 미완료)', default=False)),
                ('expires_at', models.DateTimeField(db_comment='인증 코드 만료 시각')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='인증 코드 생성 일시')),
            ],
            options={
                'db_table': 'email_verification',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserDeviceConnection',
            fields=[
                ('connection_id', models.AutoField(db_comment='연결 고유 식별자', primary_key=True, serialize=False)),
                ('connection_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('device_alias', models.CharField(blank=True, db_comment='사용자가 지정한 별칭', max_length=20, null=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True, db_comment='연결 생성 일시')),
                ('deleted_at', models.DateTimeField(blank=True, db_comment='연결 삭제 일시', null=True)),
                ('is_active', models.BooleanField(db_comment='연결 활성화 상태', default=False)),
                ('device', models.ForeignKey(db_column='device_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.device')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_device_connection',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserManualPreset',
            fields=[
                ('preset_id', models.AutoField(db_comment='프리셋 고유 식별자 (PK)', primary_key=True, serialize=False)),
                ('up', models.IntegerField(db_comment='상방향 이동값', default=0)),
                ('down', models.IntegerField(db_comment='하방향 이동값', default=0)),
                ('left', models.IntegerField(db_comment='좌측 이동값', default=0)),
                ('right', models.IntegerField(db_comment='우측 이동값', default=0)),
                ('tilt_up', models.IntegerField(db_comment='Tilt 상방향 회전값', default=0)),
                ('tilt_down', models.IntegerField(db_comment='Tilt 하방향 회전값', default=0)),
                ('has_left', models.IntegerField(db_comment='HAS 좌측 회전값', default=0)),
                ('has_right', models.IntegerField(db_comment='HAS 우측 회전값', default=0)),
                ('distance', models.IntegerField(db_comment='거리값 (0-100)', default=50)),
                ('is_active', models.BooleanField(db_comment='활성화된 프리셋 여부', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='프리셋 생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='프리셋 수정 일시')),
                ('connection', models.ForeignKey(db_column='connection_id', db_comment='기기 연결 ID (FK)', on_delete=django.db.models.deletion.CASCADE, to='accounts.userdeviceconnection')),
                ('user', models.ForeignKey(db_column='user_id', db_comment='사용자 ID (FK)', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_manual_preset',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.AutoField(db_comment='세션 고유 식별자 (PK)', primary_key=True, serialize=False)),
                ('robot_status', models.CharField(db_comment='로봇 상태 (IDLE, TRACKING, MOVING, ASIDE)', default='IDLE', max_length=20)),
                ('last_voice_command', models.CharField(blank=True, db_comment='마지막 음성 명령', max_length=100, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_comment='세션 시작 일시')),
                ('ended_at', models.DateTimeField(blank=True, db_comment='세션 종료 일시', null=True)),
                ('end_reason', models.CharField(blank=True, db_comment='세션 종료 사유 (LOGOUT, TIMEOUT, DEVICE_DISCONNECTED 등)', max_length=20, null=True)),
                ('connection', models.ForeignKey(db_column='connection_id', db_comment='기기 연결 ID (FK)', on_delete=django.db.models.deletion.CASCADE, to='accounts.userdeviceconnection')),
                ('user', models.ForeignKey(db_column='user_id', db_comment='사용자 ID (FK)', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'session',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('token_id', models.AutoField(db_comment='비밀번호 재설정 토큰 고유 식별자 (PK)', primary_key=True, serialize=False)),
                ('token', models.CharField(db_comment='비밀번호 재설정 토큰 문자열', max_length=255, unique=True)),
                ('expires_at', models.DateTimeField(db_comment='토큰 만료 시각')),
                ('used', models.BooleanField(db_comment='토큰 사용 여부 (True: 사용됨, False: 미사용)', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='토큰 생성 일시')),
                ('user', models.ForeignKey(db_column='user_id', db_comment='사용자 ID (FK)', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'password_reset_token',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BiometricLog',
            fields=[
                ('biometric_history_id', models.AutoField(db_comment='이력 고유 식별자', primary_key=True, serialize=False)),
                ('change_type', models.CharField(db_comment='face_update / voice_update', max_length=20)),
                ('previous_vector', models.JSONField(blank=True, db_comment='변경 전 벡터', null=True)),
                ('new_vector', models.JSONField(blank=True, db_comment='변경 후 벡터', null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('change_reason', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'biometric_log',
                'managed': True,
            },
        ),
    ]
