"""
Django settings for server project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from datetime import timedelta

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'
# ALLOWED_HOSTS = ["i14a104.p.ssafy.io", "localhost", "127.0.0.1", "localhost:8080", "127.0.0.1:8080"]
ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',  # 블랙리스트 기능
    'corsheaders',
    'drf_spectacular',    
    'accounts',
    'channels',
    'channels_redis',

]

AUTH_USER_MODEL = 'accounts.User'

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'server.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'server.wsgi.application'

ASGI_APPLICATION = 'server.asgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
        'OPTIONS': {
            'charset': 'utf8mb4',
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        }
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators


PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher', # 1순위: 표준 BCrypt
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',       # 2순위: 백업용
]




AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ko-hans'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

CORS_ALLOWED_ORIGINS = [
    "http://i14a104.p.ssafy.io:8080",   # Django 서버 자체
    "http://localhost:3000",             # React Native 개발
    "http://10.0.2.2:8081",              # Android 에뮬레이터
    # "http://70.12.245.122:5000",         # 젯슨 서버
    "http://172.20.10.3:5000",         # 핫스팟
]

# 인증 헤더 허용
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Preflight 요청 캐시 시간 (초)
CORS_PREFLIGHT_MAX_AGE = 86400  # 24시간


# 개발 중에는 모두 허용
CORS_ALLOW_ALL_ORIGINS = True

# 개발이 끝나면 
# # DEBUG 모드에 따라 CORS 설정 분기
# if DEBUG:
#     # 개발 환경: 모든 Origin 허용
#     CORS_ALLOW_ALL_ORIGINS = True
# else:
#     # 프로덕션 환경: 특정 Origin만 허용
#     CORS_ALLOWED_ORIGINS = [
#         "https://yourdomain.com",
#         "https://api.yourdomain.com",
#     ]
    
#     # 또는 정규식 패턴으로 허용
#     # CORS_ALLOWED_ORIGIN_REGEXES = [
#     #     r"^https://.*\.yourdomain\.com$",
#     # ]

# CSRF 설정
CSRF_TRUSTED_ORIGINS = [
    'http://i14a104.p.ssafy.io:8080',
    'http://i14a104.p.ssafy.io',
]

# 캐시 설정 (Redis)
# CACHES = {
#     'default': {
#         'BACKEND': 'django_redis.cache.RedisCache',
#         'LOCATION': 'redis://127.0.0.1:6379/1',
#         'OPTIONS': {
#             'CLIENT_CLASS': 'django_redis.client.DefaultClient',
#         }
#     }
# }


CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}


# 세션 설정
SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
SESSION_CACHE_ALIAS = 'default'
SESSION_COOKIE_AGE = 1800


REST_FRAMEWORK = {
    # 1. 권한 설정 (현재 모든 접근 허용 상태)
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    
    # 2. Swagger(Spectacular)를 사용하기 위한 스키마 클래스 등록
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    
    # 3. (추후 추가될) 인증 설정 - JWT 등을 쓸 때 필요합니다
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
}


SIMPLE_JWT = {
    # Access Token 유효 기간 (1시간)
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    
    # Refresh Token 유효 기간 (7일)
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    
    # Refresh Token 회전 설정 (새로운 Refresh Token 발급)
    'ROTATE_REFRESH_TOKENS': True,
    
    # 사용된 Refresh Token 블랙리스트 등록
    'BLACKLIST_AFTER_ROTATION': True,
    
    # 알고리즘
    'ALGORITHM': 'HS256',
    
    # 서명 키 (settings.SECRET_KEY 사용)
    'SIGNING_KEY': SECRET_KEY,
    
    # 검증 키 (비대칭 암호화 사용 시)
    'VERIFYING_KEY': None,
    
    # 토큰 접두사
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    
    # 사용자 식별 필드
    'USER_ID_FIELD': 'user_id',
    'USER_ID_CLAIM': 'user_id',
    
    # 토큰 타입
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    
    # JTI (JWT ID) 클레임
    'JTI_CLAIM': 'jti',
    
    # Sliding Token 설정 (사용하지 않음)
    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}

# 이메일 설정 (Gmail SMTP)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)
EMAIL_TIMEOUT = 30

# 개발 모드에서는 콘솔 출력만 사용
if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

SPECTACULAR_SETTINGS = {
    'TITLE': 'SARVIS API Project',
    'DESCRIPTION': '라즈베리 파이 & 스마트폰 연동 보안 시스템 API',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    # Swagger에서 'Authorize' 버튼을 통해 JWT 토큰을 넣고 테스트하고 싶을 때 사용
    'COMPONENT_SPLIT_PATCH': True,
    'COMPONENT_SPLIT_REQUEST': True,
}

# Channels 설정
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [(os.getenv('REDIS_HOST', '127.0.0.1'), int(os.getenv('REDIS_PORT', 6379)))],
        },
    },
}

# Celery 설정 (세션 타임아웃 체크 등 비동기 작업)
CELERY_BROKER_URL = 'redis://127.0.0.1:6379/0'
CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Seoul'

# Celery Beat 스케줄 설정
CELERY_BEAT_SCHEDULE = {
    'check-session-timeout': {
        'task': 'accounts.tasks.check_session_timeout',
        'schedule': 60.0,  # 60초마다 실행
    },
}

# 로깅 설정
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '[{levelname}] {message}',
            'style': '{',
        },
        'heartbeat': {
            'format': '❤️ [HEARTBEAT] {asctime} {message}',
            'style': '{',
        },
        'websocket': {
            'format': '🔌 [WEBSOCKET] {asctime} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'heartbeat_file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'heartbeat.log',
            'formatter': 'heartbeat',
        },
        'websocket_file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'websocket.log',
            'formatter': 'websocket',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'DEBUG',
        },
        'accounts': {
            'handlers': ['console', 'heartbeat_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'accounts.app_consumer': {
            'handlers': ['console'],
            'level': 'DEBUG',  # 하트비트 DEBUG 레벨 로그도 표시
            'propagate': False,
        },
        'accounts.consumers': {
            'handlers': ['console'],
            'level': 'DEBUG',  # 하트비트 DEBUG 레벨 로그도 표시
            'propagate': False,
        },
        'accounts.websocket_logger': {
            'handlers': ['console', 'websocket_file'],
            'level': 'DEBUG',  # 모든 웹소켓 관련 로그 표시
            'propagate': False,
        },
    },
}
