export const SarvisTheme = {
  colors: {
    primary: '#7B61FF',
    primaryDark: '#6B51EF',
    primaryLight: '#F3F0FF',
    success: '#10b981',
    successLight: '#ecfdf5',
    warning: '#f59e0b',
    warningLight: '#fffbeb',
    danger: '#ef4444',
    dangerLight: '#fef2f2',
    bg: '#f8fafc',
    card: '#ffffff',
    text: '#1e293b',
    textLight: '#64748b',
    textMuted: '#94a3b8',
    border: '#E2E8F0',
  },
  radius: {
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
  },
};
