# Generated by Django 4.2.7 on 2026-02-08 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('login_id', models.CharField(db_comment='사용자가 입력한 ID', max_length=20, unique=True)),
                ('uid', models.UUIDField(db_column='UID', default=uuid.uuid4, editable=False, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('nickname', models.CharField(max_length=20)),
                ('face_vectors', models.JSONField(db_comment='face_vectors VECTOR(512) x 5', default=list)),
                ('voice_vectors', models.JSONField(blank=True, db_comment='voice_vectors VECTOR(256) x 4', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='회원가입 일시')),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_comment='계정 활성화 상태', default=True)),
                ('is_staff', models.BooleanField(db_comment='관리자 페이지 접근 권한', default=False)),
                ('is_superuser', models.BooleanField(db_comment='모든 권한', default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deletion_reason', models.CharField(blank=True, choices=[('INCONVENIENT', '사용이 불편함'), ('PRIVACY', '개인정보 유출 우려'), ('NOT_USED', '자주 사용하지 않음'), ('OTHER', '기타')], db_comment='탈퇴 사유', max_length=20, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'user',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('verification_id', models.AutoField(db_comment='이메일 인증 고유 식별자 (PK)', primary_key=True, serialize=False)),
                ('email', models.EmailField(db_comment='인증 대상 이메일 주소', max_length=100)),
                ('verification_code', models.CharField(db_comment='6자리 인증 코드', max_length=6)),
                ('is_verified', models.BooleanField(db_comment='인증 완료 여부', default=False)),
                ('expires_at', models.DateTimeField(db_comment='인증 코드 만료 시각')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'email_verification',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('device_id', models.AutoField(db_comment='기기 고유 식별자', primary_key=True, serialize=False)),
                ('device_name', models.CharField(db_comment='기기 고유 이름', max_length=50)),
                ('device_type', models.CharField(blank=True, db_comment='디바이스 기종', max_length=50, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'phone',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sarvis',
            fields=[
                ('sarvis_id', models.AutoField(db_comment='싸비스 고유 식별자', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sarvis',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserDeviceConnection',
            fields=[
                ('connection_id', models.AutoField(db_comment='연결 고유 식별자', primary_key=True, serialize=False)),
                ('connection_uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='API 식별용 (DB 스키마에는 없지만 API 편의상 유지)', unique=True)),
                ('device_alias', models.CharField(blank=True, db_comment='사용자가 지정한 별칭', max_length=20, null=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True, db_comment='연결 생성 일시')),
                ('deleted_at', models.DateTimeField(blank=True, db_comment='연결 삭제 일시', null=True)),
                ('is_active', models.BooleanField(db_comment='연결 활성화 상태', default=False)),
                ('phone', models.ForeignKey(db_column='device_id', db_comment='기기 고유 식별자', on_delete=django.db.models.deletion.CASCADE, to='accounts.phone')),
                ('sarvis', models.ForeignKey(db_column='sarvis_id', db_comment='싸비스 고유 식별자', on_delete=django.db.models.deletion.CASCADE, to='accounts.sarvis')),
                ('user', models.ForeignKey(db_column='user_id', db_comment='싸비스 고유 식별자', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_device_connection',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.AutoField(db_comment='세션 고유 식별자', primary_key=True, serialize=False)),
                ('session_uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='API 식별용', unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_comment='세션 시작 일시')),
                ('ended_at', models.DateTimeField(blank=True, db_comment='세션 종료 일시 (NULL = 사용중)', null=True)),
                ('last_heartbeat', models.DateTimeField(blank=True, db_comment='마지막 하트비트 수신 시간 (사용 안 함)', null=True)),
                ('connection', models.ForeignKey(db_column='connection_id', db_comment='연결 고유 식별자', on_delete=django.db.models.deletion.CASCADE, to='accounts.userdeviceconnection')),
            ],
            options={
                'db_table': 'session',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Preset',
            fields=[
                ('preset_id', models.AutoField(primary_key=True, serialize=False)),
                ('servo1', models.IntegerField()),
                ('servo2', models.IntegerField()),
                ('servo3', models.IntegerField()),
                ('servo4', models.IntegerField()),
                ('servo5', models.IntegerField()),
                ('servo6', models.IntegerField()),
                ('preset_name', models.CharField(blank=True, db_comment='설정 이름', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='설정 생성 일시')),
                ('is_active', models.BooleanField(db_comment='현재 사용 중인 설정인지', default=False)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'preset',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('token_id', models.AutoField(db_comment='비밀번호 재설정 토큰 고유 식별자 (PK)', primary_key=True, serialize=False)),
                ('token', models.CharField(db_comment='비밀번호 재설정 토큰 문자열', max_length=255, unique=True)),
                ('expires_at', models.DateTimeField(db_comment='토큰 만료 시각')),
                ('used', models.BooleanField(db_comment='토큰 사용 여부', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'password_reset_token',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CommandLog',
            fields=[
                ('command_log_id', models.AutoField(db_comment='사용자 명령 로그 고유 식별자', primary_key=True, serialize=False)),
                ('command_type', models.CharField(db_comment='play_video, volume_up 등', max_length=50)),
                ('command_content', models.TextField(blank=True, db_comment='명령 상세 내용', null=True)),
                ('is_success', models.BooleanField(db_comment='명령 실행 성공 여부', null=True)),
                ('error_message', models.TextField(blank=True, db_comment='실패 시 오류 메시지', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='명령 발생 일시')),
                ('session', models.ForeignKey(db_column='session_id', db_comment='세션 고유 식별자', on_delete=django.db.models.deletion.CASCADE, to='accounts.session')),
            ],
            options={
                'db_table': 'command_log',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BiometricLog',
            fields=[
                ('biometric_history_id', models.AutoField(db_comment='이력 고유 식별자', primary_key=True, serialize=False)),
                ('change_type', models.CharField(db_comment='face_update / voice_update', max_length=50)),
                ('previous_vector', models.JSONField(blank=True, db_comment='변경 전 벡터', null=True)),
                ('new_vector', models.JSONField(blank=True, db_comment='변경 후 벡터', null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('change_reason', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'biometric_log',
                'managed': True,
            },
        ),
    ]
